/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import com.mysql.jdbc.PreparedStatement;
import com.sun.jndi.ldap.Connection;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Mauricio
 */
public class jflogin extends javax.swing.JInternalFrame {

    java.sql.Connection conn = new BDConexao().connect();

    /**
     * Creates new form jflogin
     */
    public jflogin() {
        setFrameIcon(new ImageIcon("C:\\Users\\Mauricio\\Documents\\NetBeansProjects\\SoftwareJava\\src\\interfaces\\icones\\ebella.png"));
        //setFrameIcon(null); 
        initComponents();

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        CTusuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CTsenha = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        BTlogar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        CBmostrarchar = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setTitle("Área Restrita");
        setPreferredSize(new java.awt.Dimension(640, 480));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.black));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ebella.png"))); // NOI18N
        jPanel1.add(jLabel2, new java.awt.GridBagConstraints());

        jLabel3.setText("INSERIR USUÁRIO E SENHA PARA ACESSAR A ÁREA RESTRITA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText("<html><body><br></body></html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setText("<html><body><br></body></html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel7.setText("Usuário: ");

        CTusuario.setName("CTusuario"); // NOI18N
        CTusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CTusuarioActionPerformed(evt);
            }
        });
        CTusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CTusuarioKeyPressed(evt);
            }
        });

        jLabel8.setText(" *");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CTusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(1, 1, 1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CTusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(3, 3, 3))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jPanel2, gridBagConstraints);

        jLabel9.setText("Senha: ");

        jLabel10.setText(" *");

        CTsenha.setName("CTsenha"); // NOI18N
        CTsenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CTsenhaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CTsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(1, 1, 1))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(CTsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jPanel3, gridBagConstraints);

        BTlogar.setText("ENTRAR");
        BTlogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTlogarActionPerformed(evt);
            }
        });

        jButton2.setText("LIMPAR CAMPOS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(BTlogar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTlogar)
                    .addComponent(jButton2))
                .addGap(3, 3, 3))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jPanel4, gridBagConstraints);

        CBmostrarchar.setText("Mostrar Caracteres");
        CBmostrarchar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBmostrarcharActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(CBmostrarchar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 141;
        gridBagConstraints.ipady = 77;
        gridBagConstraints.insets = new java.awt.Insets(5, 342, 407, 343);
        getContentPane().add(jPanel1, gridBagConstraints);

        jLabel1.setText("<html><body><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br></body></html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel1, gridBagConstraints);
        getContentPane().add(jLabel6, new java.awt.GridBagConstraints());

        jMenu1.setText("Arquivo");

        jMenuItem1.setText("Configurações");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Fechar Programa");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //FUNÇÃO VALIDAR CAMPOS
    public void Validar() {
        //AÇÕES BOTÃO PARA VALIDAR CAMPOS
        if (CTusuario.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O Campo Usuário esta em branco!", "Atenção!", 1);
            CTusuario.requestFocus();
        } else if (CTsenha.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O Campo Senha esta em branco!", "Atenção!", 1);
            CTsenha.requestFocus();
        } else {
            //VERIFICANDO USUÁRIO E SENHA

            try {

                //SELECT NO BANCO DE DADOS
                String selectTableSQL = "SELECT * FROM ebella_administradores";
                Statement statement = conn.createStatement();
                ResultSet rs = statement.executeQuery(selectTableSQL);
                while (rs.next()) {
                    String userid = rs.getString("usuario");
                    String username = rs.getString("senha");

                    if (CTusuario.getText().equals(rs.getString("usuario")) && CTsenha.getText().equals(rs.getString("senha"))) {

                        //OPTION PANE COM TIMER                
                        JOptionPane meuJOPane = new JOptionPane("Logando no Sistema...");
                        final JDialog dialog = meuJOPane.createDialog(null, "Atenção!");
                        dialog.setModal(true);
                        Timer timer = new Timer(2 * 1000, new ActionListener() {
                            public void actionPerformed(ActionEvent ev) {
                                dialog.dispose();
                            }
                        });
                        timer.start();
                        dialog.setVisible(true);
                        timer.stop();
                        //FIM DO OPTION PANE           

                        //FIM DA FUNÇÃO
                        dispose();

                        //CHAMA FORM DE CADASTROS
                        jfcadastros_vend framecadastro = new jfcadastros_vend();
                        Principal.jfprincipal.add(framecadastro);
                        framecadastro.setVisible(true);
                        //INICIO DO MAXIMIZAR
                        try {
                            framecadastro.setMaximum(true);
                        } catch (PropertyVetoException ex) {
                            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    //FIM DO MAXIMIZAR

                        //TORNA MENU VISIVEL
                        Principal.BarraMenu.setVisible(true);

                    } else {

                        JOptionPane.showMessageDialog(null, "Usuário e Senha Inválidos!", "Atenção!", 1);
                        //AÇÕES LIMPAR CAMPOS
                        CTusuario.setText("");
                        CTsenha.setText("");
                        CTusuario.requestFocus();
                    }

                }

            } catch (SQLException | HeadlessException E) {

                JOptionPane.showMessageDialog(null, "Usuário Inexistente!", "Atenção!", 1);

            }

        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //AÇÕES LIMPAR CAMPOS
        CTusuario.setText("");
        CTsenha.setText("");
        CTusuario.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BTlogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTlogarActionPerformed
        //CHAMA FUNÇÃO VALIDAR
        Validar();
    }//GEN-LAST:event_BTlogarActionPerformed

    private void CTusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CTusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CTusuarioActionPerformed

    private void CBmostrarcharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBmostrarcharActionPerformed
        //MOSTRAR CARACTERES DO CAMPO SENHA
        if (CBmostrarchar.isSelected()) {
            CTsenha.setEchoChar((char) 0);
        } else {
            CTsenha.setEchoChar('*');
        }
        //FIM
    }//GEN-LAST:event_CBmostrarcharActionPerformed

    private void CTusuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CTusuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //CHAMA FUNÇÃO VALIDAR
            Validar();
        }
    }//GEN-LAST:event_CTusuarioKeyPressed

       
    private void CTsenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CTsenhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //CHAMA FUNÇÃO VALIDAR
            Validar();
        }
    }//GEN-LAST:event_CTsenhaKeyPressed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
         System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTlogar;
    private javax.swing.JCheckBox CBmostrarchar;
    private javax.swing.JPasswordField CTsenha;
    private javax.swing.JTextField CTusuario;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
